nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization' , "ngrok-skip-browser-warning"]
        expose_headers: ['Link',"ngrok-skip-browser-warning"]
        max_age: 3600
    paths:
        '^/': ~
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'Content-Type', 'Authorization', "ngrok-skip-browser-warning" ]
            allow_methods: [ 'POST', 'GET', 'PUT', 'DELETE', 'PATCH', 'OPTIONS' ]
            expose_headers: ['Link', 'Location', "ngrok-skip-browser-warning"]
            max_age: 3600