# Generated by Django 5.0.6 on 2024-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="commune",
            field=models.CharField(
                choices=[
                    ("1", "Bandalungwa"),
                    ("2", "Barumbu"),
                    ("3", "Bumbu"),
                    ("4", "Gombe"),
                    ("5", "Kalamu"),
                    ("6", "Kasa-Vubu"),
                    ("7", "Kimbanseke"),
                    ("8", "Kinshasa"),
                    ("9", "Kintambo"),
                    ("10", "Kisenso"),
                    ("11", "Lemba"),
                    ("12", "Limete"),
                    ("13", "Lingwala"),
                    ("14", "Makala"),
                    ("15", "Maluku"),
                    ("16", "Masina"),
                    ("17", "Matete"),
                    ("18", "Mont-Ngafula"),
                    ("19", "Ndjili"),
                    ("20", "Ngaba"),
                    ("21", "Ngaliema"),
                    ("22", "Ngiri-Ngiri"),
                    ("23", "Nsele"),
                    ("24", "Selembao"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="quartier",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
