# Generated by Django 5.0.6 on 2024-05-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_user_commune_user_quartier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="commune",
            field=models.CharField(
                choices=[
                    ("Bandalungwa", "Bandalungwa"),
                    ("Barumbu", "Barumbu"),
                    ("Bumbu", "Bumbu"),
                    ("Gombe", "Gombe"),
                    ("Kalamu", "Kalamu"),
                    ("Kasa-Vubu", "Kasa-Vubu"),
                    ("Kimbanseke", "Kimbanseke"),
                    ("Kinshasa", "Kinshasa"),
                    ("Kintambo", "Kintambo"),
                    ("Kisenso", "Kisenso"),
                    ("Lemba", "Lemba"),
                    ("Limete", "Limete"),
                    ("Lingwala", "Lingwala"),
                    ("Makala", "Makala"),
                    ("Maluku", "Maluku"),
                    ("Masina", "Masina"),
                    ("Matete", "Matete"),
                    ("Mont-Ngafula", "Mont-Ngafula"),
                    ("Ndjili", "Ndjili"),
                    ("Ngaba", "Ngaba"),
                    ("Ngaliema", "Ngaliema"),
                    ("Ngiri-Ngiri", "Ngiri-Ngiri"),
                    ("Nsele", "Nsele"),
                    ("Selembao", "Selembao"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
