# Generated by Django 5.0.6 on 2024-05-21 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentaire",
            name="post",
        ),
        migrations.RemoveField(
            model_name="commentaire",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.AddField(
            model_name="commentaire",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="Son post",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
