# Generated by Django 5.0.6 on 2024-05-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_commentaire_post_remove_commentaire_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commenters',
        ),
        migrations.AddField(
            model_name='post',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.zone'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
